spring:
  profiles.active: 

---

spring:
  application:
   name: builder
  datasource:
    url: jdbc:h2:mem:sampletest;MODE=MySQL
    username: root
    password: mypassword
    driverClassName: org.h2.Driver
    hikari:
      idleTimeout: 30000
      connectionTimeout: 180000
      maxLifetime: 1800000
      pool-name: defaultProfileConnectionPool
      auto-commit: false
      
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 7979
  
badges: 
  github: 
    issues: "[![GitHub issues](https://img.shields.io/github/issues/Akash-Mittal/REPONAME.svg)](https://github.com/Akash-Mittal/REPONAME/issues)" 
    forks: "[![GitHub forks](https://img.shields.io/github/forks/Akash-Mittal/REPONAME.svg)](https://github.com/Akash-Mittal/REPONAME/network)"
    stars:  "[![GitHub stars](https://img.shields.io/github/stars/Akash-Mittal/REPONAME.svg)](https://github.com/Akash-Mittal/REPONAME/stargazers)"
    license:  "[![GitHub license](https://img.shields.io/github/license/Akash-Mittal/REPONAME.svg)](https://github.com/Akash-Mittal/REPONAME/blob/master/LICENSE)"
  sonar:
    measure:
  lgtm:
    alerts:
    grade:
  travis:
    status:   
  config:
    placeholder: REPONAME
---

spring:
  profiles: development
  application:
   name: bp-wallet-server
  datasource:
   url: jdbc:mysql://localhost:3306/sys?useSSL=false&allowPublicKeyRetrieval=true
   username: root
   password: root
   driver-class-name: com.mysql.cj.jdbc.Driver
   hikari:
    idle-timeout: 1000
    maximum-pool-size: 10
    minimum-idle: 1
    idleTimeout: 3000
    connectionTimeout: 30000
    maxLifetime: 1800000
    pool-name: devProfileConnectionPool
    auto-commit: false
  jpa:
   hibernate.ddl-auto: create
   generate-ddl: true
   show-sql: true
   properties:
    hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect  
server:
  port: 8080